/*
 * This file is generated by jOOQ.
 */
package kz.beeproduct.model;


import java.util.Arrays;
import java.util.List;

import kz.beeproduct.model.tables.File;
import kz.beeproduct.model.tables.Orders;
import kz.beeproduct.model.tables.Product;
import kz.beeproduct.model.tables.ProductInOrders;
import kz.beeproduct.model.tables.Users;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1988092619;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.file</code>.
     */
    public final File FILE = File.FILE;

    /**
     * The table <code>public.orders</code>.
     */
    public final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>public.product</code>.
     */
    public final Product PRODUCT = Product.PRODUCT;

    /**
     * The table <code>public.product_in_orders</code>.
     */
    public final ProductInOrders PRODUCT_IN_ORDERS = ProductInOrders.PRODUCT_IN_ORDERS;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.HONEYBEE_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            File.FILE,
            Orders.ORDERS,
            Product.PRODUCT,
            ProductInOrders.PRODUCT_IN_ORDERS,
            Users.USERS);
    }
}
