/*
 * This file is generated by jOOQ.
 */
package kz.beeproduct.model;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.honeybee_seq</code>
     */
    public static final Sequence<Long> HONEYBEE_SEQ = Internal.createSequence("honeybee_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
