/*
 * This file is generated by jOOQ.
 */
package kz.beeproduct.model;


import kz.beeproduct.model.tables.File;
import kz.beeproduct.model.tables.Orders;
import kz.beeproduct.model.tables.Product;
import kz.beeproduct.model.tables.ProductInOrders;
import kz.beeproduct.model.tables.Users;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.file</code>.
     */
    public static final File FILE = File.FILE;

    /**
     * The table <code>public.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>public.product</code>.
     */
    public static final Product PRODUCT = Product.PRODUCT;

    /**
     * The table <code>public.product_in_orders</code>.
     */
    public static final ProductInOrders PRODUCT_IN_ORDERS = ProductInOrders.PRODUCT_IN_ORDERS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
