/*
 * This file is generated by jOOQ.
 */
package kz.beeproduct.model.tables.records;


import java.time.LocalDateTime;

import kz.beeproduct.model.tables.File;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileRecord extends UpdatableRecordImpl<FileRecord> implements Record7<Long, Long, String, String, Boolean, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 444232170;

    /**
     * Setter for <code>public.file.id_</code>.
     */
    public FileRecord setId_(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.file.id_</code>.
     */
    public Long getId_() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.file.container_</code>.
     */
    public FileRecord setContainer_(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.file.container_</code>.
     */
    public Long getContainer_() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.file.filename_</code>.
     */
    public FileRecord setFilename_(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.file.filename_</code>.
     */
    public String getFilename_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.file.filepath_</code>.
     */
    public FileRecord setFilepath_(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.file.filepath_</code>.
     */
    public String getFilepath_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.file.removed_</code>.
     */
    public FileRecord setRemoved_(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.file.removed_</code>.
     */
    public Boolean getRemoved_() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.file.modified_</code>.
     */
    public FileRecord setModified_(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.file.modified_</code>.
     */
    public LocalDateTime getModified_() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.file.created_</code>.
     */
    public FileRecord setCreated_(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.file.created_</code>.
     */
    public LocalDateTime getCreated_() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, String, String, Boolean, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, String, String, Boolean, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return File.FILE.ID_;
    }

    @Override
    public Field<Long> field2() {
        return File.FILE.CONTAINER_;
    }

    @Override
    public Field<String> field3() {
        return File.FILE.FILENAME_;
    }

    @Override
    public Field<String> field4() {
        return File.FILE.FILEPATH_;
    }

    @Override
    public Field<Boolean> field5() {
        return File.FILE.REMOVED_;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return File.FILE.MODIFIED_;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return File.FILE.CREATED_;
    }

    @Override
    public Long component1() {
        return getId_();
    }

    @Override
    public Long component2() {
        return getContainer_();
    }

    @Override
    public String component3() {
        return getFilename_();
    }

    @Override
    public String component4() {
        return getFilepath_();
    }

    @Override
    public Boolean component5() {
        return getRemoved_();
    }

    @Override
    public LocalDateTime component6() {
        return getModified_();
    }

    @Override
    public LocalDateTime component7() {
        return getCreated_();
    }

    @Override
    public Long value1() {
        return getId_();
    }

    @Override
    public Long value2() {
        return getContainer_();
    }

    @Override
    public String value3() {
        return getFilename_();
    }

    @Override
    public String value4() {
        return getFilepath_();
    }

    @Override
    public Boolean value5() {
        return getRemoved_();
    }

    @Override
    public LocalDateTime value6() {
        return getModified_();
    }

    @Override
    public LocalDateTime value7() {
        return getCreated_();
    }

    @Override
    public FileRecord value1(Long value) {
        setId_(value);
        return this;
    }

    @Override
    public FileRecord value2(Long value) {
        setContainer_(value);
        return this;
    }

    @Override
    public FileRecord value3(String value) {
        setFilename_(value);
        return this;
    }

    @Override
    public FileRecord value4(String value) {
        setFilepath_(value);
        return this;
    }

    @Override
    public FileRecord value5(Boolean value) {
        setRemoved_(value);
        return this;
    }

    @Override
    public FileRecord value6(LocalDateTime value) {
        setModified_(value);
        return this;
    }

    @Override
    public FileRecord value7(LocalDateTime value) {
        setCreated_(value);
        return this;
    }

    @Override
    public FileRecord values(Long value1, Long value2, String value3, String value4, Boolean value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileRecord
     */
    public FileRecord() {
        super(File.FILE);
    }

    /**
     * Create a detached, initialised FileRecord
     */
    public FileRecord(Long id_, Long container_, String filename_, String filepath_, Boolean removed_, LocalDateTime modified_, LocalDateTime created_) {
        super(File.FILE);

        set(0, id_);
        set(1, container_);
        set(2, filename_);
        set(3, filepath_);
        set(4, removed_);
        set(5, modified_);
        set(6, created_);
    }
}
