/*
 * This file is generated by jOOQ.
 */
package kz.beeproduct.model.tables.records;


import kz.beeproduct.model.tables.ProductInOrders;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductInOrdersRecord extends TableRecordImpl<ProductInOrdersRecord> implements Record3<Long, Long, Integer> {

    private static final long serialVersionUID = -1033866919;

    /**
     * Setter for <code>public.product_in_orders.product_</code>.
     */
    public ProductInOrdersRecord setProduct_(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.product_in_orders.product_</code>.
     */
    public Long getProduct_() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.product_in_orders.order_</code>.
     */
    public ProductInOrdersRecord setOrder_(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.product_in_orders.order_</code>.
     */
    public Long getOrder_() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.product_in_orders.amount_</code>.
     */
    public ProductInOrdersRecord setAmount_(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.product_in_orders.amount_</code>.
     */
    public Integer getAmount_() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ProductInOrders.PRODUCT_IN_ORDERS.PRODUCT_;
    }

    @Override
    public Field<Long> field2() {
        return ProductInOrders.PRODUCT_IN_ORDERS.ORDER_;
    }

    @Override
    public Field<Integer> field3() {
        return ProductInOrders.PRODUCT_IN_ORDERS.AMOUNT_;
    }

    @Override
    public Long component1() {
        return getProduct_();
    }

    @Override
    public Long component2() {
        return getOrder_();
    }

    @Override
    public Integer component3() {
        return getAmount_();
    }

    @Override
    public Long value1() {
        return getProduct_();
    }

    @Override
    public Long value2() {
        return getOrder_();
    }

    @Override
    public Integer value3() {
        return getAmount_();
    }

    @Override
    public ProductInOrdersRecord value1(Long value) {
        setProduct_(value);
        return this;
    }

    @Override
    public ProductInOrdersRecord value2(Long value) {
        setOrder_(value);
        return this;
    }

    @Override
    public ProductInOrdersRecord value3(Integer value) {
        setAmount_(value);
        return this;
    }

    @Override
    public ProductInOrdersRecord values(Long value1, Long value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductInOrdersRecord
     */
    public ProductInOrdersRecord() {
        super(ProductInOrders.PRODUCT_IN_ORDERS);
    }

    /**
     * Create a detached, initialised ProductInOrdersRecord
     */
    public ProductInOrdersRecord(Long product_, Long order_, Integer amount_) {
        super(ProductInOrders.PRODUCT_IN_ORDERS);

        set(0, product_);
        set(1, order_);
        set(2, amount_);
    }
}
