/*
 * This file is generated by jOOQ.
 */
package kz.beeproduct.model.tables.records;


import kz.beeproduct.model.tables.Product;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductRecord extends UpdatableRecordImpl<ProductRecord> implements Record6<Long, String, String, String, String, Integer> {

    private static final long serialVersionUID = 1171266094;

    /**
     * Setter for <code>public.product.id_</code>.
     */
    public ProductRecord setId_(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.product.id_</code>.
     */
    public Long getId_() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.product.title_</code>.
     */
    public ProductRecord setTitle_(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.product.title_</code>.
     */
    public String getTitle_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.product.description</code>.
     */
    public ProductRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.product.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.product.avatar_</code>.
     */
    public ProductRecord setAvatar_(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.product.avatar_</code>.
     */
    public String getAvatar_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.product.path_</code>.
     */
    public ProductRecord setPath_(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.product.path_</code>.
     */
    public String getPath_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.product.price_</code>.
     */
    public ProductRecord setPrice_(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.product.price_</code>.
     */
    public Integer getPrice_() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, String, String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Product.PRODUCT.ID_;
    }

    @Override
    public Field<String> field2() {
        return Product.PRODUCT.TITLE_;
    }

    @Override
    public Field<String> field3() {
        return Product.PRODUCT.DESCRIPTION;
    }

    @Override
    public Field<String> field4() {
        return Product.PRODUCT.AVATAR_;
    }

    @Override
    public Field<String> field5() {
        return Product.PRODUCT.PATH_;
    }

    @Override
    public Field<Integer> field6() {
        return Product.PRODUCT.PRICE_;
    }

    @Override
    public Long component1() {
        return getId_();
    }

    @Override
    public String component2() {
        return getTitle_();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public String component4() {
        return getAvatar_();
    }

    @Override
    public String component5() {
        return getPath_();
    }

    @Override
    public Integer component6() {
        return getPrice_();
    }

    @Override
    public Long value1() {
        return getId_();
    }

    @Override
    public String value2() {
        return getTitle_();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public String value4() {
        return getAvatar_();
    }

    @Override
    public String value5() {
        return getPath_();
    }

    @Override
    public Integer value6() {
        return getPrice_();
    }

    @Override
    public ProductRecord value1(Long value) {
        setId_(value);
        return this;
    }

    @Override
    public ProductRecord value2(String value) {
        setTitle_(value);
        return this;
    }

    @Override
    public ProductRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ProductRecord value4(String value) {
        setAvatar_(value);
        return this;
    }

    @Override
    public ProductRecord value5(String value) {
        setPath_(value);
        return this;
    }

    @Override
    public ProductRecord value6(Integer value) {
        setPrice_(value);
        return this;
    }

    @Override
    public ProductRecord values(Long value1, String value2, String value3, String value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductRecord
     */
    public ProductRecord() {
        super(Product.PRODUCT);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(Long id_, String title_, String description, String avatar_, String path_, Integer price_) {
        super(Product.PRODUCT);

        set(0, id_);
        set(1, title_);
        set(2, description);
        set(3, avatar_);
        set(4, path_);
        set(5, price_);
    }
}
