/*
 * This file is generated by jOOQ.
 */
package kz.beeproduct.model.tables.records;


import kz.beeproduct.model.tables.ProductInOrders;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductInOrdersRecord extends TableRecordImpl<ProductInOrdersRecord> implements Record4<Long, Long, Integer, Boolean> {

    private static final long serialVersionUID = 711930832;

    /**
     * Setter for <code>public.product_in_orders.product_</code>.
     */
    public ProductInOrdersRecord setProduct_(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.product_in_orders.product_</code>.
     */
    public Long getProduct_() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.product_in_orders.order_</code>.
     */
    public ProductInOrdersRecord setOrder_(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.product_in_orders.order_</code>.
     */
    public Long getOrder_() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.product_in_orders.amount_</code>.
     */
    public ProductInOrdersRecord setAmount_(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.product_in_orders.amount_</code>.
     */
    public Integer getAmount_() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.product_in_orders.removed_</code>.
     */
    public ProductInOrdersRecord setRemoved_(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.product_in_orders.removed_</code>.
     */
    public Boolean getRemoved_() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, Integer, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, Integer, Boolean> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ProductInOrders.PRODUCT_IN_ORDERS.PRODUCT_;
    }

    @Override
    public Field<Long> field2() {
        return ProductInOrders.PRODUCT_IN_ORDERS.ORDER_;
    }

    @Override
    public Field<Integer> field3() {
        return ProductInOrders.PRODUCT_IN_ORDERS.AMOUNT_;
    }

    @Override
    public Field<Boolean> field4() {
        return ProductInOrders.PRODUCT_IN_ORDERS.REMOVED_;
    }

    @Override
    public Long component1() {
        return getProduct_();
    }

    @Override
    public Long component2() {
        return getOrder_();
    }

    @Override
    public Integer component3() {
        return getAmount_();
    }

    @Override
    public Boolean component4() {
        return getRemoved_();
    }

    @Override
    public Long value1() {
        return getProduct_();
    }

    @Override
    public Long value2() {
        return getOrder_();
    }

    @Override
    public Integer value3() {
        return getAmount_();
    }

    @Override
    public Boolean value4() {
        return getRemoved_();
    }

    @Override
    public ProductInOrdersRecord value1(Long value) {
        setProduct_(value);
        return this;
    }

    @Override
    public ProductInOrdersRecord value2(Long value) {
        setOrder_(value);
        return this;
    }

    @Override
    public ProductInOrdersRecord value3(Integer value) {
        setAmount_(value);
        return this;
    }

    @Override
    public ProductInOrdersRecord value4(Boolean value) {
        setRemoved_(value);
        return this;
    }

    @Override
    public ProductInOrdersRecord values(Long value1, Long value2, Integer value3, Boolean value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductInOrdersRecord
     */
    public ProductInOrdersRecord() {
        super(ProductInOrders.PRODUCT_IN_ORDERS);
    }

    /**
     * Create a detached, initialised ProductInOrdersRecord
     */
    public ProductInOrdersRecord(Long product_, Long order_, Integer amount_, Boolean removed_) {
        super(ProductInOrders.PRODUCT_IN_ORDERS);

        set(0, product_);
        set(1, order_);
        set(2, amount_);
        set(3, removed_);
    }
}
