/*
 * This file is generated by jOOQ.
 */
package kz.beeproduct.model.tables.records;


import kz.beeproduct.model.tables.TgUser;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TgUserRecord extends UpdatableRecordImpl<TgUserRecord> implements Record5<Long, Integer, String, String, String> {

    private static final long serialVersionUID = -1933665308;

    /**
     * Setter for <code>public.tg_user.id_</code>.
     */
    public TgUserRecord setId_(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.tg_user.id_</code>.
     */
    public Long getId_() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tg_user.chat_id_</code>.
     */
    public TgUserRecord setChatId_(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.tg_user.chat_id_</code>.
     */
    public Integer getChatId_() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.tg_user.username_</code>.
     */
    public TgUserRecord setUsername_(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.tg_user.username_</code>.
     */
    public String getUsername_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tg_user.first_name_</code>.
     */
    public TgUserRecord setFirstName_(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.tg_user.first_name_</code>.
     */
    public String getFirstName_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tg_user.role_</code>.
     */
    public TgUserRecord setRole_(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.tg_user.role_</code>.
     */
    public String getRole_() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Integer, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Integer, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TgUser.TG_USER.ID_;
    }

    @Override
    public Field<Integer> field2() {
        return TgUser.TG_USER.CHAT_ID_;
    }

    @Override
    public Field<String> field3() {
        return TgUser.TG_USER.USERNAME_;
    }

    @Override
    public Field<String> field4() {
        return TgUser.TG_USER.FIRST_NAME_;
    }

    @Override
    public Field<String> field5() {
        return TgUser.TG_USER.ROLE_;
    }

    @Override
    public Long component1() {
        return getId_();
    }

    @Override
    public Integer component2() {
        return getChatId_();
    }

    @Override
    public String component3() {
        return getUsername_();
    }

    @Override
    public String component4() {
        return getFirstName_();
    }

    @Override
    public String component5() {
        return getRole_();
    }

    @Override
    public Long value1() {
        return getId_();
    }

    @Override
    public Integer value2() {
        return getChatId_();
    }

    @Override
    public String value3() {
        return getUsername_();
    }

    @Override
    public String value4() {
        return getFirstName_();
    }

    @Override
    public String value5() {
        return getRole_();
    }

    @Override
    public TgUserRecord value1(Long value) {
        setId_(value);
        return this;
    }

    @Override
    public TgUserRecord value2(Integer value) {
        setChatId_(value);
        return this;
    }

    @Override
    public TgUserRecord value3(String value) {
        setUsername_(value);
        return this;
    }

    @Override
    public TgUserRecord value4(String value) {
        setFirstName_(value);
        return this;
    }

    @Override
    public TgUserRecord value5(String value) {
        setRole_(value);
        return this;
    }

    @Override
    public TgUserRecord values(Long value1, Integer value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TgUserRecord
     */
    public TgUserRecord() {
        super(TgUser.TG_USER);
    }

    /**
     * Create a detached, initialised TgUserRecord
     */
    public TgUserRecord(Long id_, Integer chatId_, String username_, String firstName_, String role_) {
        super(TgUser.TG_USER);

        set(0, id_);
        set(1, chatId_);
        set(2, username_);
        set(3, firstName_);
        set(4, role_);
    }
}
