/*
 * This file is generated by jOOQ.
 */
package kz.beeproduct.model.tables.records;


import kz.beeproduct.model.tables.Users;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record8<String, String, Integer, Integer, Integer, String, String, String> {

    private static final long serialVersionUID = 1447302461;

    /**
     * Setter for <code>public.users.login_</code>.
     */
    public UsersRecord setLogin_(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.users.login_</code>.
     */
    public String getLogin_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.users.password_</code>.
     */
    public UsersRecord setPassword_(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.users.password_</code>.
     */
    public String getPassword_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.users.entrance_</code>.
     */
    public UsersRecord setEntrance_(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.users.entrance_</code>.
     */
    public Integer getEntrance_() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.users.floor_</code>.
     */
    public UsersRecord setFloor_(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.users.floor_</code>.
     */
    public Integer getFloor_() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.users.flat_</code>.
     */
    public UsersRecord setFlat_(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.users.flat_</code>.
     */
    public Integer getFlat_() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.users.session_</code>.
     */
    public UsersRecord setSession_(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.users.session_</code>.
     */
    public String getSession_() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.users.address_</code>.
     */
    public UsersRecord setAddress_(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.users.address_</code>.
     */
    public String getAddress_() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.users.phone_</code>.
     */
    public UsersRecord setPhone_(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.users.phone_</code>.
     */
    public String getPhone_() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<String, String, Integer, Integer, Integer, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<String, String, Integer, Integer, Integer, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Users.USERS.LOGIN_;
    }

    @Override
    public Field<String> field2() {
        return Users.USERS.PASSWORD_;
    }

    @Override
    public Field<Integer> field3() {
        return Users.USERS.ENTRANCE_;
    }

    @Override
    public Field<Integer> field4() {
        return Users.USERS.FLOOR_;
    }

    @Override
    public Field<Integer> field5() {
        return Users.USERS.FLAT_;
    }

    @Override
    public Field<String> field6() {
        return Users.USERS.SESSION_;
    }

    @Override
    public Field<String> field7() {
        return Users.USERS.ADDRESS_;
    }

    @Override
    public Field<String> field8() {
        return Users.USERS.PHONE_;
    }

    @Override
    public String component1() {
        return getLogin_();
    }

    @Override
    public String component2() {
        return getPassword_();
    }

    @Override
    public Integer component3() {
        return getEntrance_();
    }

    @Override
    public Integer component4() {
        return getFloor_();
    }

    @Override
    public Integer component5() {
        return getFlat_();
    }

    @Override
    public String component6() {
        return getSession_();
    }

    @Override
    public String component7() {
        return getAddress_();
    }

    @Override
    public String component8() {
        return getPhone_();
    }

    @Override
    public String value1() {
        return getLogin_();
    }

    @Override
    public String value2() {
        return getPassword_();
    }

    @Override
    public Integer value3() {
        return getEntrance_();
    }

    @Override
    public Integer value4() {
        return getFloor_();
    }

    @Override
    public Integer value5() {
        return getFlat_();
    }

    @Override
    public String value6() {
        return getSession_();
    }

    @Override
    public String value7() {
        return getAddress_();
    }

    @Override
    public String value8() {
        return getPhone_();
    }

    @Override
    public UsersRecord value1(String value) {
        setLogin_(value);
        return this;
    }

    @Override
    public UsersRecord value2(String value) {
        setPassword_(value);
        return this;
    }

    @Override
    public UsersRecord value3(Integer value) {
        setEntrance_(value);
        return this;
    }

    @Override
    public UsersRecord value4(Integer value) {
        setFloor_(value);
        return this;
    }

    @Override
    public UsersRecord value5(Integer value) {
        setFlat_(value);
        return this;
    }

    @Override
    public UsersRecord value6(String value) {
        setSession_(value);
        return this;
    }

    @Override
    public UsersRecord value7(String value) {
        setAddress_(value);
        return this;
    }

    @Override
    public UsersRecord value8(String value) {
        setPhone_(value);
        return this;
    }

    @Override
    public UsersRecord values(String value1, String value2, Integer value3, Integer value4, Integer value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(String login_, String password_, Integer entrance_, Integer floor_, Integer flat_, String session_, String address_, String phone_) {
        super(Users.USERS);

        set(0, login_);
        set(1, password_);
        set(2, entrance_);
        set(3, floor_);
        set(4, flat_);
        set(5, session_);
        set(6, address_);
        set(7, phone_);
    }
}
